spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
  application:
    name: grupo37
    
#logging:
#  config: # TODO: add config
#  exception-conversion-word: # TODO: add config
#  file.path: # TODO: add config
#  file.name: # TODO: add config
#  pattern:
#    console: # TODO: add config 
#    file: # TODO: add config
#    level: # TODO: add config
